//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Java.Interop;
using Java.Net;

namespace Java.Nio.Channels {

	partial class ServerSocketChannel
	{
		INetworkChannel? INetworkChannel.Bind (SocketAddress? p0) => Bind (p0);

		public unsafe global::Java.Lang.Object? GetOption (global::Java.Net.ISocketOption? p0)
		{
			const string __id = "getOption.(Ljava/net/SocketOption;)Ljava/lang/Object;";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (p0);
				var __rm = _members.InstanceMethods.InvokeNonvirtualObjectMethod (__id, this, __args);
				return global::Java.Interop.JniEnvironment.Runtime.ValueManager.GetValue<global::Java.Lang.Object> (ref __rm, JniObjectReferenceOptions.CopyAndDispose);
			} finally {
				global::System.GC.KeepAlive (p0);
			}
		}

		INetworkChannel? INetworkChannel.SetOption (ISocketOption? p0, Lang.Object? p1) => SetOption (p0, p1);
	}

	// Metadata.xml XPath class reference: path="/api/package[@name='java.nio.channels']/class[@name='ServerSocketChannel']"
	[global::Java.Interop.JniTypeSignature ("java/nio/channels/ServerSocketChannel", GenerateJavaPeer=false, InvokerType=typeof (ServerSocketChannelInvoker))]
	public abstract partial class ServerSocketChannel : global::Java.Nio.Channels.Spi.AbstractSelectableChannel, global::Java.Nio.Channels.INetworkChannel {
		static readonly JniPeerMembers _members = new JniPeerMembers ("java/nio/channels/ServerSocketChannel", typeof (ServerSocketChannel));

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		protected ServerSocketChannel (ref JniObjectReference reference, JniObjectReferenceOptions options) : base (ref reference, options)
		{
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='java.nio.channels']/class[@name='ServerSocketChannel']/constructor[@name='ServerSocketChannel' and count(parameter)=1 and parameter[1][@type='java.nio.channels.spi.SelectorProvider']]"
		[global::Java.Interop.JniConstructorSignature ("(Ljava/nio/channels/spi/SelectorProvider;)V")]
		protected unsafe ServerSocketChannel (global::Java.Nio.Channels.Spi.SelectorProvider? provider) : base (ref *InvalidJniObjectReference, JniObjectReferenceOptions.None)
		{
			const string __id = "(Ljava/nio/channels/spi/SelectorProvider;)V";

			if (PeerReference.IsValid)
				return;

			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (provider);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				Construct (ref __r, JniObjectReferenceOptions.CopyAndDispose);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
				global::System.GC.KeepAlive (provider);
			}
		}

		public abstract global::Java.Net.SocketAddress? LocalAddress {
			// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels']/class[@name='ServerSocketChannel']/method[@name='getLocalAddress' and count(parameter)=0]"
			[global::Java.Interop.JniMethodSignature ("getLocalAddress", "()Ljava/net/SocketAddress;")]
			get; 
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels']/class[@name='ServerSocketChannel']/method[@name='accept' and count(parameter)=0]"
		public abstract global::Java.Nio.Channels.SocketChannel? Accept ();

		// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels']/class[@name='ServerSocketChannel']/method[@name='bind' and count(parameter)=1 and parameter[1][@type='java.net.SocketAddress']]"
		[global::Java.Interop.JniMethodSignature ("bind", "(Ljava/net/SocketAddress;)Ljava/nio/channels/ServerSocketChannel;")]
		public unsafe global::Java.Nio.Channels.ServerSocketChannel? Bind (global::Java.Net.SocketAddress? local)
		{
			const string __id = "bind.(Ljava/net/SocketAddress;)Ljava/nio/channels/ServerSocketChannel;";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (local);
				var __rm = _members.InstanceMethods.InvokeNonvirtualObjectMethod (__id, this, __args);
				return global::Java.Interop.JniEnvironment.Runtime.ValueManager.GetValue<global::Java.Nio.Channels.ServerSocketChannel> (ref __rm, JniObjectReferenceOptions.CopyAndDispose);
			} finally {
				global::System.GC.KeepAlive (local);
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels']/class[@name='ServerSocketChannel']/method[@name='bind' and count(parameter)=2 and parameter[1][@type='java.net.SocketAddress'] and parameter[2][@type='int']]"
		public abstract global::Java.Nio.Channels.ServerSocketChannel? Bind (global::Java.Net.SocketAddress? p0, int p1);

		// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels']/class[@name='ServerSocketChannel']/method[@name='open' and count(parameter)=0]"
		[global::Java.Interop.JniMethodSignature ("open", "()Ljava/nio/channels/ServerSocketChannel;")]
		public static unsafe global::Java.Nio.Channels.ServerSocketChannel? Open ()
		{
			const string __id = "open.()Ljava/nio/channels/ServerSocketChannel;";
			try {
				var __rm = _members.StaticMethods.InvokeObjectMethod (__id, null);
				return global::Java.Interop.JniEnvironment.Runtime.ValueManager.GetValue<global::Java.Nio.Channels.ServerSocketChannel> (ref __rm, JniObjectReferenceOptions.CopyAndDispose);
			} finally {
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels']/class[@name='ServerSocketChannel']/method[@name='open' and count(parameter)=1 and parameter[1][@type='java.net.ProtocolFamily']]"
		[global::Java.Interop.JniMethodSignature ("open", "(Ljava/net/ProtocolFamily;)Ljava/nio/channels/ServerSocketChannel;")]
		public static unsafe global::Java.Nio.Channels.ServerSocketChannel? Open (global::Java.Net.IProtocolFamily? family)
		{
			const string __id = "open.(Ljava/net/ProtocolFamily;)Ljava/nio/channels/ServerSocketChannel;";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (family);
				var __rm = _members.StaticMethods.InvokeObjectMethod (__id, __args);
				return global::Java.Interop.JniEnvironment.Runtime.ValueManager.GetValue<global::Java.Nio.Channels.ServerSocketChannel> (ref __rm, JniObjectReferenceOptions.CopyAndDispose);
			} finally {
				global::System.GC.KeepAlive (family);
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels']/class[@name='ServerSocketChannel']/method[@name='setOption' and count(parameter)=2 and parameter[1][@type='java.net.SocketOption&lt;T&gt;'] and parameter[2][@type='T']]"
		[global::Java.Interop.JavaTypeParameters (new string [] {"T"})]
		public abstract global::Java.Nio.Channels.ServerSocketChannel? SetOption (global::Java.Net.ISocketOption? p0, global::Java.Lang.Object? p1);

		// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels']/class[@name='ServerSocketChannel']/method[@name='socket' and count(parameter)=0]"
		public abstract global::Java.Net.ServerSocket? Socket ();

		// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels']/class[@name='ServerSocketChannel']/method[@name='validOps' and count(parameter)=0]"
		[return:global::Android.Runtime.GeneratedEnum]
		[global::Java.Interop.JniMethodSignature ("validOps", "()I")]
		public override sealed unsafe global::Java.Nio.Channels.Operations ValidOps ()
		{
			const string __id = "validOps.()I";
			try {
				var __rm = _members.InstanceMethods.InvokeNonvirtualInt32Method (__id, this, null);
				return (global::Java.Nio.Channels.Operations) __rm!;
			} finally {
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels']/interface[@name='NetworkChannel']/method[@name='supportedOptions' and count(parameter)=0]"
		public abstract global::Java.Util.ISet? SupportedOptions ();

	}

	[global::Java.Interop.JniTypeSignature ("java/nio/channels/ServerSocketChannel", GenerateJavaPeer=false)]
	internal partial class ServerSocketChannelInvoker : ServerSocketChannel {
		public ServerSocketChannelInvoker (ref JniObjectReference reference, JniObjectReferenceOptions options) : base (ref reference, options)
		{
		}

		static readonly JniPeerMembers _members = new JniPeerMembers ("java/nio/channels/ServerSocketChannel", typeof (ServerSocketChannelInvoker));

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		public override unsafe global::Java.Net.SocketAddress? LocalAddress {
			// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels']/class[@name='ServerSocketChannel']/method[@name='getLocalAddress' and count(parameter)=0]"
			get {
				const string __id = "getLocalAddress.()Ljava/net/SocketAddress;";
				try {
					var __rm = _members.InstanceMethods.InvokeAbstractObjectMethod (__id, this, null);
					return global::Java.Interop.JniEnvironment.Runtime.ValueManager.GetValue<global::Java.Net.SocketAddress> (ref __rm, JniObjectReferenceOptions.CopyAndDispose);
				} finally {
				}
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels']/class[@name='ServerSocketChannel']/method[@name='accept' and count(parameter)=0]"
		[global::Java.Interop.JniMethodSignature ("accept", "()Ljava/nio/channels/SocketChannel;")]
		public override unsafe global::Java.Nio.Channels.SocketChannel? Accept ()
		{
			const string __id = "accept.()Ljava/nio/channels/SocketChannel;";
			try {
				var __rm = _members.InstanceMethods.InvokeAbstractObjectMethod (__id, this, null);
				return global::Java.Interop.JniEnvironment.Runtime.ValueManager.GetValue<global::Java.Nio.Channels.SocketChannel> (ref __rm, JniObjectReferenceOptions.CopyAndDispose);
			} finally {
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels']/class[@name='ServerSocketChannel']/method[@name='bind' and count(parameter)=2 and parameter[1][@type='java.net.SocketAddress'] and parameter[2][@type='int']]"
		[global::Java.Interop.JniMethodSignature ("bind", "(Ljava/net/SocketAddress;I)Ljava/nio/channels/ServerSocketChannel;")]
		public override unsafe global::Java.Nio.Channels.ServerSocketChannel? Bind (global::Java.Net.SocketAddress? p0, int p1)
		{
			const string __id = "bind.(Ljava/net/SocketAddress;I)Ljava/nio/channels/ServerSocketChannel;";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [2];
				__args [0] = new JniArgumentValue (p0);
				__args [1] = new JniArgumentValue (p1);
				var __rm = _members.InstanceMethods.InvokeAbstractObjectMethod (__id, this, __args);
				return global::Java.Interop.JniEnvironment.Runtime.ValueManager.GetValue<global::Java.Nio.Channels.ServerSocketChannel> (ref __rm, JniObjectReferenceOptions.CopyAndDispose);
			} finally {
				global::System.GC.KeepAlive (p0);
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels']/class[@name='ServerSocketChannel']/method[@name='setOption' and count(parameter)=2 and parameter[1][@type='java.net.SocketOption&lt;T&gt;'] and parameter[2][@type='T']]"
		[global::Java.Interop.JniMethodSignature ("setOption", "(Ljava/net/SocketOption;Ljava/lang/Object;)Ljava/nio/channels/ServerSocketChannel;")]
		[global::Java.Interop.JavaTypeParameters (new string [] {"T"})]
		public override unsafe global::Java.Nio.Channels.ServerSocketChannel? SetOption (global::Java.Net.ISocketOption? p0, global::Java.Lang.Object? p1)
		{
			const string __id = "setOption.(Ljava/net/SocketOption;Ljava/lang/Object;)Ljava/nio/channels/ServerSocketChannel;";
			var native_p1 = (p1?.PeerReference ?? default);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [2];
				__args [0] = new JniArgumentValue (p0);
				__args [1] = new JniArgumentValue (native_p1);
				var __rm = _members.InstanceMethods.InvokeAbstractObjectMethod (__id, this, __args);
				return global::Java.Interop.JniEnvironment.Runtime.ValueManager.GetValue<global::Java.Nio.Channels.ServerSocketChannel> (ref __rm, JniObjectReferenceOptions.CopyAndDispose);
			} finally {
				global::System.GC.KeepAlive (p0);
				global::System.GC.KeepAlive (p1);
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels']/class[@name='ServerSocketChannel']/method[@name='socket' and count(parameter)=0]"
		[global::Java.Interop.JniMethodSignature ("socket", "()Ljava/net/ServerSocket;")]
		public override unsafe global::Java.Net.ServerSocket? Socket ()
		{
			const string __id = "socket.()Ljava/net/ServerSocket;";
			try {
				var __rm = _members.InstanceMethods.InvokeAbstractObjectMethod (__id, this, null);
				return global::Java.Interop.JniEnvironment.Runtime.ValueManager.GetValue<global::Java.Net.ServerSocket> (ref __rm, JniObjectReferenceOptions.CopyAndDispose);
			} finally {
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels']/interface[@name='NetworkChannel']/method[@name='supportedOptions' and count(parameter)=0]"
		[global::Java.Interop.JniMethodSignature ("supportedOptions", "()Ljava/util/Set;")]
		public override unsafe global::Java.Util.ISet? SupportedOptions ()
		{
			const string __id = "supportedOptions.()Ljava/util/Set;";
			try {
				var __rm = _members.InstanceMethods.InvokeAbstractObjectMethod (__id, this, null);
				return global::Java.Interop.JniEnvironment.Runtime.ValueManager.GetValue<global::Java.Util.ISet> (ref __rm, JniObjectReferenceOptions.CopyAndDispose);
			} finally {
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels.spi']/class[@name='AbstractSelectableChannel']/method[@name='implCloseSelectableChannel' and count(parameter)=0]"
		[global::Java.Interop.JniMethodSignature ("implCloseSelectableChannel", "()V")]
		protected override unsafe void ImplCloseSelectableChannel ()
		{
			const string __id = "implCloseSelectableChannel.()V";
			try {
				_members.InstanceMethods.InvokeAbstractVoidMethod (__id, this, null);
			} finally {
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.nio.channels.spi']/class[@name='AbstractSelectableChannel']/method[@name='implConfigureBlocking' and count(parameter)=1 and parameter[1][@type='boolean']]"
		[global::Java.Interop.JniMethodSignature ("implConfigureBlocking", "(Z)V")]
		protected override unsafe void ImplConfigureBlocking (bool p0)
		{
			const string __id = "implConfigureBlocking.(Z)V";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (p0 ? (sbyte)1 : (sbyte)0);
				_members.InstanceMethods.InvokeAbstractVoidMethod (__id, this, __args);
			} finally {
			}
		}

	}
}
