//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Java.Interop;

namespace Java.Util {

	// Metadata.xml XPath class reference: path="/api/package[@name='java.util']/class[@name='PriorityQueue']"
	[global::Java.Interop.JniTypeSignature ("java/util/PriorityQueue", GenerateJavaPeer=false)]
	[global::Java.Interop.JavaTypeParameters (new string [] {"E"})]
	public partial class PriorityQueue : global::Java.Util.AbstractQueue, global::Java.IO.ISerializable {
		static readonly JniPeerMembers _members = new JniPeerMembers ("java/util/PriorityQueue", typeof (PriorityQueue));

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		protected PriorityQueue (ref JniObjectReference reference, JniObjectReferenceOptions options) : base (ref reference, options)
		{
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='java.util']/class[@name='PriorityQueue']/constructor[@name='PriorityQueue' and count(parameter)=0]"
		[global::Java.Interop.JniConstructorSignature ("()V")]
		public unsafe PriorityQueue () : base (ref *InvalidJniObjectReference, JniObjectReferenceOptions.None)
		{
			const string __id = "()V";

			if (PeerReference.IsValid)
				return;

			try {
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), null);
				Construct (ref __r, JniObjectReferenceOptions.CopyAndDispose);
				_members.InstanceMethods.FinishCreateInstance (__id, this, null);
			} finally {
			}
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='java.util']/class[@name='PriorityQueue']/constructor[@name='PriorityQueue' and count(parameter)=1 and parameter[1][@type='int']]"
		[global::Java.Interop.JniConstructorSignature ("(I)V")]
		public unsafe PriorityQueue (int initialCapacity) : base (ref *InvalidJniObjectReference, JniObjectReferenceOptions.None)
		{
			const string __id = "(I)V";

			if (PeerReference.IsValid)
				return;

			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (initialCapacity);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				Construct (ref __r, JniObjectReferenceOptions.CopyAndDispose);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
			}
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='java.util']/class[@name='PriorityQueue']/constructor[@name='PriorityQueue' and count(parameter)=2 and parameter[1][@type='int'] and parameter[2][@type='java.util.Comparator&lt;? super E&gt;']]"
		[global::Java.Interop.JniConstructorSignature ("(ILjava/util/Comparator;)V")]
		public unsafe PriorityQueue (int initialCapacity, global::Java.Util.IComparator? comparator) : base (ref *InvalidJniObjectReference, JniObjectReferenceOptions.None)
		{
			const string __id = "(ILjava/util/Comparator;)V";

			if (PeerReference.IsValid)
				return;

			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [2];
				__args [0] = new JniArgumentValue (initialCapacity);
				__args [1] = new JniArgumentValue (comparator);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				Construct (ref __r, JniObjectReferenceOptions.CopyAndDispose);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
				global::System.GC.KeepAlive (comparator);
			}
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='java.util']/class[@name='PriorityQueue']/constructor[@name='PriorityQueue' and count(parameter)=1 and parameter[1][@type='java.util.Collection&lt;? extends E&gt;']]"
		[global::Java.Interop.JniConstructorSignature ("(Ljava/util/Collection;)V")]
		public unsafe PriorityQueue (global::Java.Util.ICollection? c) : base (ref *InvalidJniObjectReference, JniObjectReferenceOptions.None)
		{
			const string __id = "(Ljava/util/Collection;)V";

			if (PeerReference.IsValid)
				return;

			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (c);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				Construct (ref __r, JniObjectReferenceOptions.CopyAndDispose);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
				global::System.GC.KeepAlive (c);
			}
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='java.util']/class[@name='PriorityQueue']/constructor[@name='PriorityQueue' and count(parameter)=1 and parameter[1][@type='java.util.Comparator&lt;? super E&gt;']]"
		[global::Java.Interop.JniConstructorSignature ("(Ljava/util/Comparator;)V")]
		public unsafe PriorityQueue (global::Java.Util.IComparator? comparator) : base (ref *InvalidJniObjectReference, JniObjectReferenceOptions.None)
		{
			const string __id = "(Ljava/util/Comparator;)V";

			if (PeerReference.IsValid)
				return;

			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (comparator);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				Construct (ref __r, JniObjectReferenceOptions.CopyAndDispose);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
				global::System.GC.KeepAlive (comparator);
			}
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='java.util']/class[@name='PriorityQueue']/constructor[@name='PriorityQueue' and count(parameter)=1 and parameter[1][@type='java.util.PriorityQueue&lt;? extends E&gt;']]"
		[global::Java.Interop.JniConstructorSignature ("(Ljava/util/PriorityQueue;)V")]
		public unsafe PriorityQueue (global::Java.Util.PriorityQueue? c) : base (ref *InvalidJniObjectReference, JniObjectReferenceOptions.None)
		{
			const string __id = "(Ljava/util/PriorityQueue;)V";

			if (PeerReference.IsValid)
				return;

			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (c);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				Construct (ref __r, JniObjectReferenceOptions.CopyAndDispose);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
				global::System.GC.KeepAlive (c);
			}
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='java.util']/class[@name='PriorityQueue']/constructor[@name='PriorityQueue' and count(parameter)=1 and parameter[1][@type='java.util.SortedSet&lt;? extends E&gt;']]"
		[global::Java.Interop.JniConstructorSignature ("(Ljava/util/SortedSet;)V")]
		public unsafe PriorityQueue (global::Java.Util.ISortedSet? c) : base (ref *InvalidJniObjectReference, JniObjectReferenceOptions.None)
		{
			const string __id = "(Ljava/util/SortedSet;)V";

			if (PeerReference.IsValid)
				return;

			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (c);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				Construct (ref __r, JniObjectReferenceOptions.CopyAndDispose);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
				global::System.GC.KeepAlive (c);
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.util']/class[@name='PriorityQueue']/method[@name='comparator' and count(parameter)=0]"
		[global::Java.Interop.JniMethodSignature ("comparator", "()Ljava/util/Comparator;")]
		public virtual unsafe global::Java.Util.IComparator? Comparator ()
		{
			const string __id = "comparator.()Ljava/util/Comparator;";
			try {
				var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, null);
				return global::Java.Interop.JniEnvironment.Runtime.ValueManager.GetValue<global::Java.Util.IComparator> (ref __rm, JniObjectReferenceOptions.CopyAndDispose);
			} finally {
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.util']/class[@name='PriorityQueue']/method[@name='forEach' and count(parameter)=1 and parameter[1][@type='java.util.function.Consumer&lt;? super E&gt;']]"
		[global::Java.Interop.JniMethodSignature ("forEach", "(Ljava/util/function/Consumer;)V")]
		public virtual unsafe void ForEach (global::Java.Util.Function.IConsumer? action)
		{
			const string __id = "forEach.(Ljava/util/function/Consumer;)V";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (action);
				_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, __args);
			} finally {
				global::System.GC.KeepAlive (action);
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.util']/class[@name='PriorityQueue']/method[@name='iterator' and count(parameter)=0]"
		[global::Java.Interop.JniMethodSignature ("iterator", "()Ljava/util/Iterator;")]
		public override unsafe global::Java.Util.IIterator? Iterator ()
		{
			const string __id = "iterator.()Ljava/util/Iterator;";
			try {
				var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, null);
				return global::Java.Interop.JniEnvironment.Runtime.ValueManager.GetValue<global::Java.Util.IIterator> (ref __rm, JniObjectReferenceOptions.CopyAndDispose);
			} finally {
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.util']/class[@name='PriorityQueue']/method[@name='offer' and count(parameter)=1 and parameter[1][@type='E']]"
		[global::Java.Interop.JniMethodSignature ("offer", "(Ljava/lang/Object;)Z")]
		public unsafe bool Offer (global::Java.Lang.Object? e)
		{
			const string __id = "offer.(Ljava/lang/Object;)Z";
			var native_e = (e?.PeerReference ?? default);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (native_e);
				var __rm = _members.InstanceMethods.InvokeVirtualBooleanMethod (__id, this, __args);
				return __rm;
			} finally {
				global::System.GC.KeepAlive (e);
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.util']/class[@name='PriorityQueue']/method[@name='peek' and count(parameter)=0]"
		[global::Java.Interop.JniMethodSignature ("peek", "()Ljava/lang/Object;")]
		public unsafe global::Java.Lang.Object? Peek ()
		{
			const string __id = "peek.()Ljava/lang/Object;";
			try {
				var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, null);
				return global::Java.Interop.JniEnvironment.Runtime.ValueManager.GetValue<global::Java.Lang.Object>(ref __rm, JniObjectReferenceOptions.CopyAndDispose);
			} finally {
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.util']/class[@name='PriorityQueue']/method[@name='poll' and count(parameter)=0]"
		[global::Java.Interop.JniMethodSignature ("poll", "()Ljava/lang/Object;")]
		public unsafe global::Java.Lang.Object? Poll ()
		{
			const string __id = "poll.()Ljava/lang/Object;";
			try {
				var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, null);
				return global::Java.Interop.JniEnvironment.Runtime.ValueManager.GetValue<global::Java.Lang.Object>(ref __rm, JniObjectReferenceOptions.CopyAndDispose);
			} finally {
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.util']/class[@name='PriorityQueue']/method[@name='removeIf' and count(parameter)=1 and parameter[1][@type='java.util.function.Predicate&lt;? super E&gt;']]"
		[global::Java.Interop.JniMethodSignature ("removeIf", "(Ljava/util/function/Predicate;)Z")]
		public virtual unsafe bool RemoveIf (global::Java.Util.Function.IPredicate? filter)
		{
			const string __id = "removeIf.(Ljava/util/function/Predicate;)Z";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (filter);
				var __rm = _members.InstanceMethods.InvokeVirtualBooleanMethod (__id, this, __args);
				return __rm;
			} finally {
				global::System.GC.KeepAlive (filter);
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='java.util']/class[@name='PriorityQueue']/method[@name='size' and count(parameter)=0]"
		[global::Java.Interop.JniMethodSignature ("size", "()I")]
		public override unsafe int Size ()
		{
			const string __id = "size.()I";
			try {
				var __rm = _members.InstanceMethods.InvokeVirtualInt32Method (__id, this, null);
				return __rm;
			} finally {
			}
		}

	}
}
